spring.application.name=user-management-service

server.port=8081

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/user_management_service
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# service-discovery
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Kafka Topics
kafka.topic.user.signup.notification=user_signup_notification
kafka.topic.password.reset.notification=password_reset_notification